# Generated by Django 6.0 on 2026-02-13 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono')),
                ('nie', models.CharField(max_length=10, unique=True, verbose_name='NIE')),
                ('nc', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NC')),
                ('fecha_nacimiento', models.CharField(verbose_name='Fecha de nacimiento')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('rol', models.CharField(choices=[('DOCTOR', 'Doctor'), ('PACIENTE', 'Paciente')], default='PACIENTE', verbose_name='Estado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
                'ordering': ('nie',),
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(choices=[('PRO', 'Proceso'), ('COM', 'Completado'), ('EXP', 'Expirado'), ('CAN', 'Cancelado')], default='PRO', verbose_name='Estado')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('nie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='NIE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
