<<<<<<< HEAD
# Generated by Django 6.0 on 2026-02-18 10:45
=======
# Generated by Django 6.0 on 2026-02-13 18:33
>>>>>>> 4ed433d9b957733948918b1ca96783a7760c85e3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
<<<<<<< HEAD
            field=models.CharField(choices=[('DOC', 'Doctor'), ('PAC', 'Paciente')], default='PAC', verbose_name='ROL'),
=======
            field=models.CharField(choices=[('DOC', 'Doctor'), ('PAC', 'Paciente')], default='PAC', verbose_name='Estado'),
>>>>>>> 4ed433d9b957733948918b1ca96783a7760c85e3
        ),
    ]
