# Generated by Django 6.0 on 2026-02-19 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial', '0002_usuarios_is_active_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'ordering': ['-creado'], 'verbose_name': 'Citas', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AddField(
            model_name='citas',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citas',
            name='nie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NIE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='citas',
            table='citas',
        ),
    ]
