# Generated by Django 6.0 on 2026-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial', '0003_alter_citas_options_citas_fecha_alter_citas_nie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'ordering': ['-creado'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='citas',
            name='fecha',
            field=models.DateTimeField(default=''),
        ),
    ]
