# Generated by Django 6.0 on 2026-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial', '0004_alter_citas_options_alter_citas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='anotaciones',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Anotaciones'),
        ),
        migrations.AddField(
            model_name='citas',
            name='campo',
            field=models.TextField(choices=[('ODONTO', 'Odontologia'), ('PEDIA', 'Pediatria'), ('GERIA', 'Geriatría'), ('MED_IN', 'Medicina Interna/Clínica'), ('MED_GE', 'Medicina General'), ('OTORRI', 'Otorrinolaringología'), ('DERMA', 'Dermatología'), ('OFTAL', 'Oftalmología'), ('UROLO', 'Urología ')], default='MED_GE', max_length=6, verbose_name='Campo'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='img',
            field=models.ImageField(default='images/default.jpg', upload_to='users/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='estado',
            field=models.TextField(choices=[('PRO', 'Proceso'), ('COM', 'Completado'), ('EXP', 'Expirado'), ('CAN', 'Cancelado')], default='PRO', max_length=3, verbose_name='Estado'),
        ),
    ]
